package com.inscopelabs.abx.clipinbox.cbxdag.domain.delegation

import com.inscopelabs.abx.clipinbox.cbxdag.domain.model.Delegation
import com.inscopelabs.abx.clipinbox.cbxdag.domain.model.Manifest

// A wrapper that separates the durable archive from the ephemeral delegation state
data class DelegationEnvelope(
    val delegation: Delegation,
    val manifest: Manifest,
    val apiKey: String // generated by Cloudflare on push, filled later
)